/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPublishedRouteImport } from './routes/_authenticated/published'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedPreviewClientIdRouteImport } from './routes/_authenticated/preview.$clientId'
import { Route as AuthenticatedPortalsNewRouteImport } from './routes/_authenticated/portals.new'
import { Route as AuthenticatedPortalsPortalIdRouteImport } from './routes/_authenticated/portals.$portalId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedRoute = AuthenticatedPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreviewClientIdRoute =
  AuthenticatedPreviewClientIdRouteImport.update({
    id: '/preview/$clientId',
    path: '/preview/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalsNewRoute = AuthenticatedPortalsNewRouteImport.update({
  id: '/portals/new',
  path: '/portals/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalsPortalIdRoute =
  AuthenticatedPortalsPortalIdRouteImport.update({
    id: '/portals/$portalId',
    path: '/portals/$portalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/portals/new': typeof AuthenticatedPortalsNewRoute
  '/preview/$clientId': typeof AuthenticatedPreviewClientIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/portals/new': typeof AuthenticatedPortalsNewRoute
  '/preview/$clientId': typeof AuthenticatedPreviewClientIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/published': typeof AuthenticatedPublishedRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/_authenticated/portals/new': typeof AuthenticatedPortalsNewRoute
  '/_authenticated/preview/$clientId': typeof AuthenticatedPreviewClientIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/published'
    | '/queue'
    | '/requests'
    | '/settings'
    | '/portals/$portalId'
    | '/portals/new'
    | '/preview/$clientId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clients'
    | '/published'
    | '/queue'
    | '/requests'
    | '/settings'
    | '/'
    | '/portals/$portalId'
    | '/portals/new'
    | '/preview/$clientId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/published'
    | '/_authenticated/queue'
    | '/_authenticated/requests'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/portals/$portalId'
    | '/_authenticated/portals/new'
    | '/_authenticated/preview/$clientId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published': {
      id: '/_authenticated/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof AuthenticatedPublishedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preview/$clientId': {
      id: '/_authenticated/preview/$clientId'
      path: '/preview/$clientId'
      fullPath: '/preview/$clientId'
      preLoaderRoute: typeof AuthenticatedPreviewClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals/new': {
      id: '/_authenticated/portals/new'
      path: '/portals/new'
      fullPath: '/portals/new'
      preLoaderRoute: typeof AuthenticatedPortalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals/$portalId': {
      id: '/_authenticated/portals/$portalId'
      path: '/portals/$portalId'
      fullPath: '/portals/$portalId'
      preLoaderRoute: typeof AuthenticatedPortalsPortalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedPublishedRoute: typeof AuthenticatedPublishedRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPortalsPortalIdRoute: typeof AuthenticatedPortalsPortalIdRoute
  AuthenticatedPortalsNewRoute: typeof AuthenticatedPortalsNewRoute
  AuthenticatedPreviewClientIdRoute: typeof AuthenticatedPreviewClientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedPublishedRoute: AuthenticatedPublishedRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPortalsPortalIdRoute: AuthenticatedPortalsPortalIdRoute,
  AuthenticatedPortalsNewRoute: AuthenticatedPortalsNewRoute,
  AuthenticatedPreviewClientIdRoute: AuthenticatedPreviewClientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
